on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Create PR Message for Check List
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          message: |
            #### auto-tag를 위해 PR Title을 컨벤션에 맞춰주세요.
            [예시]
            Release 21.08.02-1
            Hotfix 21.10.24-2
          allow-repeats: false